name: Deploy React App to GitHub Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Display Node.js version
        run: node -v

      - name: Display npm version
        run: npm -v

      - name: Install dependencies
        run: npm install

      - name: Update Browserslist database
        run: npx browserslist@latest --update-db

      - name: Configure Git
        run: |
          git config --global user.email "brunobahrii27@gmail.com"
          git config --global user.name "brunobahri"

      - name: Build the React app
        run: |
          npm install -g cross-env
          cross-env CI=false npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "seu-email@exemplo.com"
          git config --global user.name "Seu Nome"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npx gh-pages -d build

      - name: Display deploy logs on failure
        if: failure()
        run: |
          echo "Deploy failed, displaying logs:"
          cat /home/runner/.npm/_logs/*-debug.log
