name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Display Node.js version
        run: node -v

      - name: Display npm version
        run: npm -v

      - name: Install dependencies
        run: npm install

      - name: Update Browserslist database
        run: npx browserslist@latest --update-db

      - name: Build the React app
        run: |
          npm install -g cross-env
          cross-env CI=false npm run build

      - name: Display build logs on failure
        if: failure()
        run: |
          echo "Build failed, displaying logs:"
          cat /home/runner/.npm/_logs/*-debug.log

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display deploy logs on failure
        if: failure()
        run: |
          echo "Deploy failed, displaying logs:"
          cat /home/runner/.npm/_logs/*-debug.log
